stages:
  vscode installed:
    description: install vscode if it is not installed
    when:
      condition:
        operator: not_contains
        command: arch -arm64e /opt/homebrew/bin/brew ls --versions --cask visual-studio-code
        compareTo: "visual-studio-code 1.63.2"
    setup:
      - command: arch -arm64e /opt/homebrew/bin/brew install homebrew/cask/visual-studio-code

  alfred installed:
    description: install alfred if it is not installed
    when:
      condition:
        operator: not_contains
        command: arch -arm64e /opt/homebrew/bin/brew ls --versions --cask alfred
        compareTo: "alfred 4"
    setup:
      - command: arch -arm64e /opt/homebrew/bin/brew install --cask alfred

  1password installed:
    description: install 1password if it is not installed
    when:
      condition:
        operator: not_contains
        command: arch -arm64e /opt/homebrew/bin/brew ls --versions --cask 1password
        compareTo: "1password 7"
    setup:
      - command: arch -arm64e /opt/homebrew/bin/brew install --cask 1password

  docker installed:
    description: install docker if it is not installed
    when:
      condition:
        operator: not_contains
        command: arch -arm64e /opt/homebrew/bin/brew ls --versions --cask docker
        compareTo: "docker 4"
    setup:
      - command: arch -arm64e /opt/homebrew/bin/brew install --cask docker

  slack installed:
    description: install slack if it is not installed
    when:
      condition:
        operator: not_contains
        command: arch -arm64e /opt/homebrew/bin/brew ls --versions --cask slack
        compareTo: "slack 4"
    setup:
      - command: arch -arm64e /opt/homebrew/bin/brew install --cask slack

  terraform installed:
    description: install terraform if it is not installed
    when:
      condition:
        operator: not_contains
        command: arch -arm64e /opt/homebrew/bin/brew ls --versions terraform
        compareTo: "terraform 1"
    setup:
      - command: arch -arm64e /opt/homebrew/bin/brew tap hashicorp/tap
      - command: arch -arm64e /opt/homebrew/bin/brew install hashicorp/tap/terraform 

  spark installed:
    description: install spark if it is not installed
    when:
      condition:
        operator: not_contains
        command: mas list
        compareTo: "1176895641"
    setup:
      - command: mas install 1176895641

  firefox-developer-edition installed:
    description: install firefox-developer-edition if it is not installed
    when:
      condition:
        operator: not_contains
        command: arch -arm64e /opt/homebrew/bin/brew ls --versions --cask firefox-developer-edition
        compareTo: "latest"
    setup:
      - command: arch -arm64e /opt/homebrew/bin/brew install homebrew/cask-versions/firefox-developer-edition

  magnet installed:
    description: install magnet if it is not installed
    when:
      condition:
        operator: not_contains
        command: mas list
        compareTo: "441258766"
    setup:
      - command: mas install 441258766

  kakaotalk installed:
    description: install kakaotalk if it is not installed
    when:
      condition:
        operator: not_contains
        command: mas list
        compareTo: "869223134"
    setup:
      - command: mas install 869223134
