stages:
  vscode installed:
    description: install vscode if it is not installed
    when:
      condition:
        operator: not_contains
        command: arch -arm64e /opt/homebrew/bin/brew ls --versions --cask visual-studio-code
        compareTo: "visual-studio-code 1.63.2"
    setup:
      - command: arch -arm64e /opt/homebrew/bin/brew install homebrew/cask/visual-studio-code

  iterm2 installed:
    description: install iterm2 if it is not installed
    when:
      condition:
        operator: not_contains
        command: arch -arm64e /opt/homebrew/bin/brew ls --versions --cask iterm2
        compareTo: "iterm2 3"
    setup:
      - command: arch -arm64e /opt/homebrew/bin/brew install homebrew/cask/iterm2


  alfred installed:
    description: install alfred if it is not installed
    when:
      condition:
        operator: not_contains
        command: arch -arm64e /opt/homebrew/bin/brew ls --versions --cask alfred
        compareTo: "alfred 4"
    setup:
      - command: arch -arm64e /opt/homebrew/bin/brew install --cask alfred

  1password installed:
    description: install 1password if it is not installed
    when:
      condition:
        operator: not_contains
        command: arch -arm64e /opt/homebrew/bin/brew ls --versions --cask 1password
        compareTo: "1password 7"
    setup:
      - command: arch -arm64e /opt/homebrew/bin/brew install --cask 1password

  docker installed:
    description: install docker if it is not installed
    when:
      condition:
        operator: not_contains
        command: arch -arm64e /opt/homebrew/bin/brew ls --versions docker
        compareTo: "docker 20"
    setup:
      - command: arch -arm64e /opt/homebrew/bin/brew install docker

  slack installed:
    description: install slack if it is not installed
    when:
      condition:
        operator: not_contains
        command: arch -arm64e /opt/homebrew/bin/brew ls --versions --cask slack
        compareTo: "slack 4"
    setup:
      - command: arch -arm64e /opt/homebrew/bin/brew install --cask slack

  terraform installed:
    description: install terraform if it is not installed
    when:
      condition:
        operator: not_contains
        command: arch -arm64e /opt/homebrew/bin/brew ls --versions terraform
        compareTo: "terraform 1"
    setup:
      - command: arch -arm64e /opt/homebrew/bin/brew tap hashicorp/tap
      - command: arch -arm64e /opt/homebrew/bin/brew install hashicorp/tap/terraform 

  spark installed:
    description: install spark if it is not installed
    when:
      condition:
        operator: not_contains
        command: mas list
        compareTo: "1176895641"
    setup:
      - command: mas install 1176895641

  firefox-developer-edition installed:
    description: install firefox-developer-edition if it is not installed
    when:
      condition:
        operator: not_contains
        command: arch -arm64e /opt/homebrew/bin/brew ls --versions --cask firefox-developer-edition
        compareTo: "latest"
    setup:
      - command: arch -arm64e /opt/homebrew/bin/brew install homebrew/cask-versions/firefox-developer-edition

  magnet installed:
    description: install magnet if it is not installed
    when:
      condition:
        operator: not_contains
        command: mas list
        compareTo: "441258766"
    setup:
      - command: mas install 441258766

  kakaotalk installed:
    description: install kakaotalk if it is not installed
    when:
      condition:
        operator: not_contains
        command: mas list
        compareTo: "869223134"
    setup:
      - command: mas install 869223134

  postman installed:
    description: install postman if it is not installed
    when:
      condition:
        operator: not_contains
        command: arch -arm64e /opt/homebrew/bin/brew ls --versions --cask postman
        compareTo: "9."
    setup:
      - command: arch -arm64e /opt/homebrew/bin/brew install --cask postman

  figma installed:
    description: install figma if it is not installed
    when:
      condition:
        operator: not_contains
        command: arch -arm64e /opt/homebrew/bin/brew ls --versions --cask figma
        compareTo: "107."
    setup:
      - command: arch -arm64e /opt/homebrew/bin/brew install --cask figma

  colima installed:
    description: install colima if it is not installed
    when:
      condition:
        operator: not_contains
        command: arch -arm64e /opt/homebrew/bin/brew ls --versions colima
        compareTo: "colima 0."
    setup:
      - command: arch -arm64e /opt/homebrew/bin/brew install colima

  kubectl installed:
    description: install kubectl if it is not installed
    when:
      condition:
        operator: not_contains
        command: arch -arm64e /opt/homebrew/bin/brew ls --versions kubectl
        compareTo: "kubectl 1."
    setup:
      - command: arch -arm64e /opt/homebrew/bin/brew install kubectl
