stages:
  vscode installed:
    description: install vscode if it is not installed
    when:
      condition:
        operator: not_contains
        command: arch -arm64e /opt/homebrew/bin/brew ls --versions --cask visual-studio-code
        compareTo: "visual-studio-code 1.63.2"
    setup:
      - command: arch -arm64e /opt/homebrew/bin/brew install homebrew/cask/visual-studio-code

